# Generated by Django 4.1.7 on 2023-08-21 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
